package tci.demo.week1.buffer;

/**
 * this is a specification for a bounded buffer (=buffer with a given, fixed size).
 * the requirements for the methods are given below.
 * <p>
 * make tests first!
 */

public interface IIntBuffer {


    /**
     * put a value in the buffer. Throw an BufferIsFullException when buffer is full
     *
     * @param val
     */

    public void put(int val) throws BufferIsFullException;

    /**
     * @return the sum of values in the buffer
     */
    public int getSum();

    /**
     * shows if buffer is full
     *
     * @return true if buffer is full, otherwise false
     */
    public boolean bufferIsFull();

    /**
     * @return nr of items put in the buffer
     */

    public int getNrOfItemsInBuffer();


    /**
     * buffersize
     *
     * @return size of the buffer.
     */
    public int getBufferSize();


    /******************************************************
     *
     *   GETTERS/SETTERS CODE IS GENERATED BY INTELLIJ,
     *   AND UNTOUCHED BY PEOPLE.
     *   THE BEHAVIOUR OF THIS CODE DOES NOT HAVE TO BE TESTED.
     *
     ********************************************************/


}


